<a href="https://colab.research.google.com/github/Prathambiradr12345/DATA-SCEINCE-PROJECTS/blob/main/fifa_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###EDA

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
fifa=pd.read_csv('fifa_ranking.csv')
matches=pd.read_csv('matches.csv')
world=pd.read_csv('world_cup.csv')

In [4]:
world

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Qatar,32,Argentina,France,Kylian Mbappé - 8,3404252,53191,64
1,2018,Russia,32,France,Croatia,Harry Kane - 6,3031768,47371,64
2,2014,Brazil,32,Germany,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,South Africa,32,Spain,Netherlands,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Germany,32,Italy,France,Miroslav Klose - 5,3352605,52384,64
5,2002,"Korea Republic, Japan",32,Brazil,Germany,Ronaldo - 8,2705337,42271,64
6,1998,France,32,France,Brazil,Davor Šuker - 6,2903477,45367,64
7,1994,United States,24,Brazil,Italy,"Hristo Stoichkov, Oleg Salenko - 6",3587538,68991,52
8,1990,Italy,24,West Germany,Argentina,Salvatore Schillaci - 6,2516215,48389,52
9,1986,Mexico,24,Argentina,West Germany,Gary Lineker - 6,2394031,46039,52
10,1982,Spain,24,Italy,West Germany,Paolo Rossi - 6,2109723,40572,52
11,1978,Argentina,16,Argentina,Netherlands,Mario Kempes - 6,1545791,40679,38
12,1974,Germany,16,West Germany,Netherlands,Grzegorz Lato - 7,1865753,49099,38
13,1970,Mexico,16,Brazil,Italy,Gerd Müller - 10,1603975,50124,32
14,1966,England,16,England,West Germany,Eusébio - 9,1563135,48848,32
15,1962,Chile,16,Brazil,Czechoslovakia,"Leonel Sánchez, Flórián Albert... - 4",893172,27912,32
16,1958,Sweden,16,Brazil,Sweden,Just Fontaine - 13,819810,23423,35
17,1954,Switzerland,16,Germany,Hungary,Sándor Kocsis - 11,768607,29562,26
18,1950,Brazil,15,Uruguay,Brazil,Ademir - 8,1045246,47511,22
19,1938,France,16,Italy,Hungary,Leônidas - 7,375700,20872,18
20,1934,Italy,16,Italy,Czechoslovakia,Oldřich Nejedlý - 5,363000,21353,17
21,1930,Uruguay,13,Uruguay,Argentina,Guillermo Stábile - 8,590549,32808,18

In [5]:
fifa

,team,team_code,association,rank,previous_rank,points,previous_points
0,Brazil,BRA,CONMEBOL,1,1,1841.30,1837.56
1,Belgium,BEL,UEFA,2,2,1816.71,1821.92
2,Argentina,ARG,CONMEBOL,3,3,1773.88,1770.65
3,France,FRA,UEFA,4,4,1759.78,1764.85
4,England,ENG,UEFA,5,5,1728.47,1737.46
...,...,...,...,...,...,...,...
206,Sri Lanka,SRI,AFC,207,207,825.25,825.25
207,US Virgin Islands,VIR,CONCACAF,208,208,823.97,823.97
208,British Virgin Islands,VGB,CONCACAF,209,209,809.32,809.32
209,Anguilla,AIA,CONCACAF,210,210,790.74,790.74
210,San Marino,SMR,UEFA,211,211,762.22,763.82

In [8]:
matches.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [9]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    object
 1   away_team                        964 non-null    object
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    object
 9   home_captain                     644 non-null    object
 10  away_manager                     964 non-null    object
 11  away_captain                     644 non-null    object
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    object
 14  Officials                        709 non-null    object
 15  Round                            964 non-null    object
 16  Date                             964 non-null    object
 17  Score                            964 non-null    object
 18  Referee                          709 non-null    object
 19  Notes                            73 non-null     object
 20  Host                             964 non-null    object
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    object
 23  away_goal                        571 non-null    object
 24  home_goal_long                   718 non-null    object
 25  away_goal_long                   571 non-null    object
 26  home_own_goal                    39 non-null     object
 27  away_own_goal                    17 non-null     object
 28  home_penalty_goal                116 non-null    object
 29  away_penalty_goal                84 non-null     object
 30  home_penalty_miss_long           6 non-null      object
 31  away_penalty_miss_long           9 non-null      object
 32  home_penalty_shootout_goal_long  34 non-null     object
 33  away_penalty_shootout_goal_long  34 non-null     object
 34  home_penalty_shootout_miss_long  24 non-null     object
 35  away_penalty_shootout_miss_long  30 non-null     object
 36  home_red_card                    51 non-null     object
 37  away_red_card                    54 non-null     object
 38  home_yellow_red_card             23 non-null     object
 39  away_yellow_red_card             31 non-null     object
 40  home_yellow_card_long            621 non-null    object
 41  away_yellow_card_long            627 non-null    object
 42  home_substitute_in_long          740 non-null    object
 43  away_substitute_in_long          747 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 331.5+ KB

In [11]:
matches['home_goal'][0]

'Ángel Di María · 36|Lionel Messi · 108'

In [12]:
matches['away_goal'][0]

'Kylian Mbappé · 81'

In [13]:
matches['home_goal_long'][0]

"['36&rsquor;|2:0|Ángel Di María|Assist:|Alexis Mac Allister', '108&rsquor;|3:2|Lionel Messi']"

In [17]:
matches['away_yellow_card_long'][0]

"['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2:2|Marcus Thuram', '90+5&rsquor;|2:2|Olivier Giroud']"

In [21]:
print(matches.shape)
print(fifa.shape)
print(world.shape)

(964, 44)
(211, 7)
(22, 9)

In [23]:
matches.isnull().sum()

home_team                            0
away_team                            0
home_score                           0
home_xg                            836
home_penalty                       929
away_score                           0
away_xg                            836
away_penalty                       929
home_manager                         0
home_captain                       320
away_manager                         0
away_captain                       320
Attendance                           0
Venue                                0
Officials                          255
Round                                0
Date                                 0
Score                                0
Referee                            255
Notes                              891
Host                                 0
Year                                 0
home_goal                          246
away_goal                          393
home_goal_long                     246
away_goal_long                     393
home_own_goal                      925
away_own_goal                      947
home_penalty_goal                  848
away_penalty_goal                  880
home_penalty_miss_long             958
away_penalty_miss_long             955
home_penalty_shootout_goal_long    930
away_penalty_shootout_goal_long    930
home_penalty_shootout_miss_long    940
away_penalty_shootout_miss_long    934
home_red_card                      913
away_red_card                      910
home_yellow_red_card               941
away_yellow_red_card               933
home_yellow_card_long              343
away_yellow_card_long              337
home_substitute_in_long            224
away_substitute_in_long            217
dtype: int64

In [24]:
fifa.isnull().sum()

team               0
team_code          0
association        0
rank               0
previous_rank      0
points             0
previous_points    0
dtype: int64

In [25]:
world.isnull().sum()

Year             0
Host             0
Teams            0
Champion         0
Runner-Up        0
TopScorrer       0
Attendance       0
AttendanceAvg    0
Matches          0
dtype: int64

In [26]:
matches.isnull().sum()/len(matches)*100

home_team                           0.000000
away_team                           0.000000
home_score                          0.000000
home_xg                            86.721992
home_penalty                       96.369295
away_score                          0.000000
away_xg                            86.721992
away_penalty                       96.369295
home_manager                        0.000000
home_captain                       33.195021
away_manager                        0.000000
away_captain                       33.195021
Attendance                          0.000000
Venue                               0.000000
Officials                          26.452282
Round                               0.000000
Date                                0.000000
Score                               0.000000
Referee                            26.452282
Notes                              92.427386
Host                                0.000000
Year                                0.000000
home_goal                          25.518672
away_goal                          40.767635
home_goal_long                     25.518672
away_goal_long                     40.767635
home_own_goal                      95.954357
away_own_goal                      98.236515
home_penalty_goal                  87.966805
away_penalty_goal                  91.286307
home_penalty_miss_long             99.377593
away_penalty_miss_long             99.066390
home_penalty_shootout_goal_long    96.473029
away_penalty_shootout_goal_long    96.473029
home_penalty_shootout_miss_long    97.510373
away_penalty_shootout_miss_long    96.887967
home_red_card                      94.709544
away_red_card                      94.398340
home_yellow_red_card               97.614108
away_yellow_red_card               96.784232
home_yellow_card_long              35.580913
away_yellow_card_long              34.958506
home_substitute_in_long            23.236515
away_substitute_in_long            22.510373
dtype: float64

In [27]:
matches.duplicated().sum()

0

In [29]:
fifa.duplicated().sum()

0

In [30]:
world.duplicated().sum()

0

In [31]:
matches['home_team'].unique()

array(['Argentina', 'Croatia', 'France', 'Morocco', 'England',
       'Netherlands', 'Portugal', 'Japan', 'Brazil', 'Korea Republic',
       'Ghana', 'Cameroon', 'Serbia', 'Canada', 'Costa Rica', 'Australia',
       'Tunisia', 'Saudi Arabia', 'Poland', 'Ecuador', 'IR Iran', 'Wales',
       'Belgium', 'Spain', 'Qatar', 'Switzerland', 'Uruguay', 'Germany',
       'Denmark', 'Mexico', 'Senegal', 'United States', 'Sweden',
       'Russia', 'Colombia', 'Panama', 'Iceland', 'Nigeria', 'Peru',
       'Egypt', 'Algeria', 'Bosnia and Herzegovina', 'Honduras', 'Italy',
       'Greece', "Côte d'Ivoire", 'Chile', 'Paraguay', 'Korea DPR',
       'Slovakia', 'Slovenia', 'South Africa', 'New Zealand', 'Ukraine',
       'Togo', 'Czech Republic', 'Serbia and Montenegro', 'Angola',
       'Trinidad and Tobago', 'Türkiye', 'China PR',
       'Republic of Ireland', 'Romania', 'Scotland', 'FR Yugoslavia',
       'Jamaica', 'Bulgaria', 'Bolivia', 'Norway', 'West Germany',
       'Yugoslavia', 'Czechoslovakia', 'Austria', 'United Arab Emirates',
       'Soviet Union', 'Northern Ireland', 'Iraq', 'Hungary',
       'Germany DR', 'Zaire', 'Haiti', 'Cuba'], dtype=object)

In [ ]:
matches['home_team']=matches['home_team'].apply(lambda x: x.replace('Germany FR', ' West Germany',))
matches['away_team']=matches['away_team'].apply(lambda x: x.replace('Germany FR', ' West Germany',))

In [32]:
#total matches
print(matches.shape[0])

964

In [34]:
len(matches)

964